// Fallback configuration for "What's New" modal

import {
  Activity,
  Anchor,
  Award,
  Beaker,
  Bell,
  Calendar,
  Camera,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Command,
  CreditCard,
  Database,
  Flag,
  Flame,
  Gift,
  Globe,
  HardDrive,
  Heart,
  Image,
  Key,
  Layout,
  Link,
  Lock,
  Map,
  MapPin,
  MessageSquare,
  Monitor,
  Moon,
  Music,
  Paperclip,
  Rocket,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sun,
  Target,
  Terminal,
  Thermometer,
  Trophy,
  Unlock,
  User,
  Users,
  Video,
  Wallet,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface WhatsNewFeature {
  icon: string;
  title: string;
  description: string;
  color: string;
  bg: string;
}

/** Every icon a "what's new" feature can use, keyed by the name stored in `feature.icon`. Single
 * source of truth for the admin editor's icon picker and the modal that renders the saved icon. */
export const WHATS_NEW_ICON_MAP: Record<string, LucideIcon> = {
  Sparkles,
  Smartphone,
  Beaker,
  Layout,
  MessageSquare,
  Globe,
  Calendar,
  Zap,
  Activity,
  Map,
  Heart,
  Target,
  Award,
  Coffee,
  Rocket,
  Gift,
  Bell,
  Shield,
  Camera,
  Music,
  Video,
  ShoppingBag,
  CreditCard,
  Wallet,
  Key,
  Lock,
  Unlock,
  Settings,
  Command,
  Terminal,
  Code,
  Cloud,
  Database,
  Server,
  HardDrive,
  Monitor,
  Image,
  Send,
  Share,
  Trophy,
  Flag,
  Anchor,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Thermometer,
  Paperclip,
  Link,
  MapPin,
  User,
  Users,
  Flame,
};

export const CURRENT_WHATS_NEW_VERSION = "v2.1";

export const WHATS_NEW_FEATURES: WhatsNewFeature[] = [
  {
    icon: "Sparkles",
    title: "Fresh New Look",
    description:
      "I've completely overhauled the UI to be cleaner, darker, and more premium. Enjoy the new aesthetic while you plan your trips.",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
  },
  {
    icon: "Smartphone",
    title: "Activities DnD",
    description:
      "I added a drag and drop feature for activities. You can now drag and drop activities to reorder them.",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    icon: "Beaker",
    title: "Beta Access",
    description:
      "You're one of the first to try out these new features. I'm still in beta, so your feedback is incredibly valuable to me!",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
  },
];
